# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-06 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '博客分类', 'verbose_name_plural': '博客分类'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '博客标签', 'verbose_name_plural': '博客标签'},
        ),
        migrations.AddField(
            model_name='entry',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='博客配图'),
        ),
    ]
