# Generated by Django 2.1.5 on 2019-01-10 12:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190108_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='博客正文'),
        ),
    ]
