# Generated by Django 2.1.5 on 2019-01-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190110_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='videourl',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='视频地址'),
        ),
    ]
