# Generated by Django 2.1.5 on 2019-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_entry_videourl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=526, verbose_name='公告内容')),
            ],
            options={
                'verbose_name': '公告内容',
                'verbose_name_plural': '公告内容',
            },
        ),
    ]
